#Load in the packages
library(Matrix)
library(lattice)
library(fdrtool)
library(rpart)
library(ggplot2)
library(affyPLM)
library(limma)
library(Biostrings)
library(Biobase)
library(genefilter)
library(oligo)
library(ggplot2)
library(grid)
library(gridExtra)
library(DESeq2)
library(simpleaffy)
library(pd.rta.1.0)
library(rae230a.db)
library(AnnotationDbi)
library(shiny)
library(heatmaply)
library("RColorBrewer")

#Set working directory
setwd("/Users/bethalexander/Desktop/university/year two/Summer placement/working directory/micrarray_data/")

#Open the CEL files in R, using oligo
#Generates a HTAFeatureSet
celpath ="/Users/bethalexander/Desktop/university/year two/Summer placement/working directory/microarray"
list = list.files(celpath,full.names=TRUE)
data = read.celfiles(list)

#PARAMETERS TO CHANGE
#How to add annotation to phenoData
ph = data@phenoData
ph
ph@data[ ,1] = c("SJ1","SJ2","SJ3","SJ4","SJ5","SJ6","wJ1","wJ2","wJ3","wJ4","wJ5","wJ6")  
ph
ph@data[ ,2] = c("strain","strain","strain","strain","strain","strain","control","control","control","control","control","control")
colnames(ph@data)[2]="source" 
ph@data
groups = ph@data$source
f = factor(groups,levels=c("strain","control"))
design = model.matrix(~ 0 + f)
colnames(design) = c("strain","control")
contrast.matrix = makeContrasts(strain-control,levels=design)
#normalisation: 
data.rma = rma(data)
data.matrix = exprs(data.rma)
colnames(data.matrix)=c("S1","S2","S3","S4","S5","S6","W1","W2","W3","W4","W5","W6")

#Now you need to tell limma which sample belongs to which group. This info is contained in the second column (the column that we called source) of the PhenoData.
data.fit = lmFit(data.matrix,design)
data.fit.con = contrasts.fit(data.fit,contrast.matrix)
data.fit.eb = eBayes(data.fit.con)
names(data.fit.eb)

#The meaning of the adjusted p-value is as follows: if you select all genes with adjusted p-value below 0.05 as DE, then the expected proportion of false positives in the selected group should be less than 5%. So if you select 100 DE genes at a false discovery rate of 0.05, only 5 of them will be false positives.
options(digits=2)
tab = topTable(data.fit.eb,coef=1,number=1000,adjust.method="BH")
head(tab)

#You have create a subset of the table generated by topTable() with adjusted p-values (last column of tab called adj.P.Val) below a threshold (in this example the threshold is set at 0.001):
topgenes = tab[tab[, "adj.P.Val"] < 0.05, ]
dim(topgenes)

#If you want to distinguish between up- and downregulated genes and you want to include a log fold change threshold, you need to create another subset of the remaining table
topups = topgenes[topgenes[, "logFC"] > 1, ]
dim(topups)
topdowns = topgenes[topgenes[, "logFC"] < -1, ]
dim(topdowns)

#How to create a list of IDs of genes that are DE according to topTable() 
IDs.up = rownames(topups)
IDs.down = rownames(topdowns)
head(IDs.down)
head(IDs.up)

#Heatmap: 
data.matrix.up = data.matrix[(rownames(topups)),]
data.matrix.down = data.matrix[(rownames(topdowns)),]



#APP:
# Define UI for data download app ----
ui <- fluidPage(
  
  # App title ----
  titlePanel("Downloading Data"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      # Input: Choose dataset ----
      selectInput("dataset", "Choose a dataset:",
                  choices = c("up-regulated", "down-regulated")),
    
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      fluidRow(plotlyOutput("heatmap",height = "4000px",width="1200px"))
      
    )
    
  )))


# Define server logic to display and download selected file ----
server <- function(input, output) {
  
  # Reactive value for selected dataset ----
  datasetInput <- reactive({
    switch(input$dataset,
           "up-regulated" = heatmaply(data.matrix.up, dendrogram = "none", Rowv = FALSE, Colv = FALSE,xlab = "Samples", ylab = "Genes", 
                                      main = "Upregulated genes",margins = c(60,100,40,20),
                                      k_col = 2, k_row = 2,colors = RdBu),
           "down-regulated" = heatmaply(data.matrix.down, dendrogram = "none", Rowv = FALSE, Colv = FALSE,xlab = "Samples", ylab = "Genes", 
                                        main = "Downregulated genes",margins = c(6, 10),
                                        k_col = 2, k_row = 2,colors = RdBu))
  })
  
  # Table of selected dataset ----
  output$heatmap <- renderPlotly({
    datasetInput()
  })

  
}

# Create Shiny app ----
shinyApp(ui, server)

write.table(sessionInfo(), sep = "\t", file = "Session Info")